name: Build and push into Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        # Path to the Dockerfile
        file: Dockerfile
        # List of tags
        tags: ${{ github.repository }}:${{ github.ref_name }}
        # Sets the target stage to build
        target: distroless
        # GitHub Token used to authenticate against a repository for Git context
        github-token: ${{ github.token }}

        # List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)
        # secrets: # optional
        # List of secret files to expose to the build (e.g., key=filename, MY_SECRET=./secret.txt)
        # secret-files: # optional
